Sitegeist:
  MagicWand:
    # the local flow command
    flowCommand: './flow'
    rsyncParams:
        # Additional params in the form of:
        # - '-shortParam' AND/OR
        # - '-shortParamShortParamShortParam' AND/OR
        # - '--longParam'
        - '-kLr'
    clonePresets: []
#      # the name of the preset for referencing on the clone:preset command
#      master: 
#        # hostname or ip of the server to clone from
#        host: ~
#        # ssh username 
#        user: ~
#        # ssh port
#        port: ~
#        # path on the remote server
#        path: ~
#        # flow-context on the remote server  
#        context: Production
#        # the flow cli command on the remote server
#        # default is the main flowCommand-Setting
#        flowCommand: ~
#        # commands to execute after cloning
#        postClone:
#         - './flow help'
